FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY . .

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=builder /app/target/*.jar /app/app.jar

CMD ["sh", "-c", "/opt/java/openjdk/bin/java -Dserver.port=${PORT:-8081} -jar /app/app.jar"]